apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: "nikhildocker28/k8s-db:latest"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  clusterIP: 10.107.180.2
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql

