apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend 
spec:
  selector:
    matchLabels:
      app: backend
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.image.containerPort}}
