apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-nodejs
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
