apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2 
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "nikhildocker28/k8s-backend:latest"
          ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  clusterIP: 10.107.180.1
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000


